### ISSUE TITLE
Bug in Node.js <= 14. No sourceMap for CSS.

### ISSUE THREAD

**Issue by Sir-Will** [webdiscus/pug-plugin#2]
Hey,

I'm using `extractCss` which is working so far, but I couldn't figure out how to enable the source map creation with this.
I have added `sourceMap: true` to css- postcss- and sass-loader, but it's not creating one.

How do I enable source map with pug plugin?

**Comment by webdiscus** [comment]
Hallo @Sir-Will,

the `pug-plugin` extract css and sourceMap from result  of the `css-loader`.

The example of `webpack.config.js` from [the test case](https://github.com/webdiscus/pug-plugin/tree/master/test/cases/entry-sass-pug-devel):

```js
const path = require('path');
const PugPlugin = require('../../../');

// if is FALSE then will be generated the sourceMap
const isProduction = process.env.NODE_ENV === 'production';

module.exports = {
  mode: isProduction ? 'production' : 'development', // <-- only in mode  'development' is generated sourceMap
  devtool: isProduction ? false : 'source-map',  // <-- if devtool is not false then is generated sourceMap

  output: {
    path: path.join(__dirname, 'public/'),
    publicPath: '/',
  },

  entry: {
    styles: './src/assets/main.scss',
    index: './src/index.pug',
  },

  plugins: [
    new PugPlugin({
      modules: [
        PugPlugin.extractCss({
          filename: isProduction ? '[name].[contenthash:8].css' : '[name].css',
        }),
      ],
    }),
  ],

  module: {
    rules: [
      {
        test: /\.(pug)$/,
        loader: PugPlugin.loader,
      },
      {
        test: /\.(css|sass|scss)$/,
        use: ['css-loader', 'sass-loader'],
      },
    ],
  },
};
```

If the `isProduction` is `false` then the sourceMap is  generated as embedded data in self css-file, like following:

```css
h1 {
  color: darkred;
}
/*# sourceURL=webpack://./src/assets/main.scss */
/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8uL3NyYy9hc3NldHMvbWFpbi5zY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUNBO0VBQ0UsY0FGTTtBQUVSIiwic291cmNlc0NvbnRlbnQiOlsiJGNvbG9yOiBkYXJrcmVkO1xuaDEge1xuICBjb2xvcjogJGNvbG9yO1xufSJdLCJzb3VyY2VSb290IjoiIn0= */
```

It's legal, supported by all browsers. Additional `*.css.map` files are no longer generated. It's very practical. Instead of two files, only one is loaded in the browser. The mapping to source of scss works fine in all browser. The mapping is only relevant for development. In Production will be generate pure css w/o sourceMap.

**Comment by Sir-Will** [comment]
Ah, I liked to have the source map enabled for production, as the file only loads with dev tools active, as far as I know.

Unfortunately, I don't see the inline sourceMap at the end of the .css file, like in your example.

This is my config:
```js
let webpackConfig = {
    entry: {
        app: './scss/app.scss',
    },
    mode: 'development',
    devtool: 'source-map',
    output: {
        publicPath: paths.dest.css
    },
    module: {
        rules: [
            {
                test: /\.scss$/,
                exclude: /node_modules/,
                use: [          // Extract and save the final CSS.
                    // Load the CSS, set url = false to prevent following urls to fonts and images.
                    { loader: "css-loader", options: { url: false, importLoaders: 1,  sourceMap: true } },
                    // Add browser prefixes and minify CSS.
                    { loader: 'postcss-loader', options: { postcssOptions: { plugins: [autoprefixer(), cssnano()] }, sourceMap: true } },
                    // Load the SCSS/SASS
                    { loader: 'sass-loader', options: { sourceMap: true } },
                ]
            }
        ],
    },
    plugins: [
        // Extract css to .css file
        new PugPlugin({
            modules: [
                PugPlugin.extractCss({
                    filename: '[name].[contenthash:8].bundle.min.css',
                    sourceMap: true
                }),
            ],
        }),
    ]
};
```

**Comment by webdiscus** [comment]
Note: the `PugPlugin.extractCss()` has not the option `sourceMap`, because the `css-loader` generate it.

P.S.: Maybe later I can implement the feature to save the sourceMap in a separate file.

**Comment by Sir-Will** [comment]
Hm, I tried your example locally under Windows and on an Ubuntu 20.04.1 LTS server.
On Windows it does have the source map at the end of the file but not on Ubuntu.

So I checked the NodeJS version and the server had `v14.18.3` while locally I have `v16.13.2` installed.
After updating the server to `v16.13.2` it was creating the source map there too.

Weird that there was no error being thrown.

Note: With the `mini-css-extract-plugin` it was creating the source map with NodeJS v14

Grüße zurück, aus der Augsburg/München Umgebung.

**Comment by Sir-Will** [comment]
Oh, and the `sourceMap: true` options for the loaders don't seem to be needed.

**Comment by webdiscus** [comment]
Thank you for the investigation! It is very important bug repport.
I will to fix it for Node.js 12, 14.

**Comment by webdiscus** [comment]
Hallo @Sir-Will,
in new version `1.3.0` is fixed the issue for node <=14.
Now the source map is saved in separate file.
Do you can please try new version and if OK close the ticket? 
Thank you!

**Comment by Sir-Will** [comment]
I no longer have NodeJS 14 installed to test it.

Does it respect the webpack `devtool` option for `inline-source-map` and `source-map`?

**Comment by webdiscus** [comment]
The new version does not depend on the node version.
All tests passed for node 12.x, 14x, 16.x, see [GitHab workflow](https://github.com/webdiscus/pug-plugin/actions/runs/1809192309).

Webpack option `devtool` is relevant for `css-loader`, the pug-plugin extract all what generates the css-loader.
Yes, the options `source-map`, `inline-source-map`, etc. works. I have tested both `source-map` and `inline-source-map`, it will be generate same .css.map file.

**Comment by webdiscus** [comment]
the problem is solved

**Comment by Sir-Will** [comment]
Hm, I just tested the source-map and when using `devtool: inline-source-map` it creates the .map file, shouldn't it inline the map if it's set to `inline-source-map`?

I thought pug-plugin is going to either create the .map file or inline the map like it was in version 1.2.4 depending on the `devtool` setting. Like webpack does for the javascript files.

**Comment by webdiscus** [comment]
Hallo @Sir-Will,
thank you for feedback. 
Inline source map is fixed In the version `1.4.3`. Now the option `devtool: inline-source-map` works.

**Comment by Sir-Will** [comment]
I updated to 1.4.3 and it's still not inlining it for me with `devtool: inline-source-map`

**Comment by webdiscus** [comment]
@Sir-Will 
can you please see the test case [devtool-inline-source-map](https://github.com/webdiscus/pug-plugin/tree/master/test/cases/devtool-inline-source-map).

[webpack.config.js](https://github.com/webdiscus/pug-plugin/blob/master/test/cases/devtool-inline-source-map/webpack.config.js)
```js
module.exports = {
  devtool: 'inline-source-map',
  ...
}
```
[expected css](https://github.com/webdiscus/pug-plugin/blob/master/test/cases/devtool-inline-source-map/expected/assets/styles.min.css) with inline (embedded source map)
```
body{color:red}
/*# sourceURL=webpack://./src/assets/main.scss */
/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjoz... */
```

What is your usage case?
Try please test local:
```
clone https://github.com/webdiscus/pug-plugin.git
cd pug-plugin
npm i
npm run test
```

**Comment by Sir-Will** [comment]
Oh, I just realized that I changed the devtool setting for my JavaScript task and not the CSS task, sorry, my bad. It's working.
