### ISSUE TITLE
Modules from HotReplacementPlugin being injected into inline JS

### ISSUE THREAD

**Issue by YUCLing** [webdiscus/pug-plugin#58]
When I'm using inline JS with `webpack-dev-server`, the inline JS code will be injected with hot replacement code from `HotReplacementPlugin` and webpack bootstrap code.

In my circumstance, the inline JS code throws an error claiming `Automatic publicPath is not supported in this browser` and stops execution.

If I run a build instead of dev server, the inline JS script works perfectly.

I have no idea how to deal with this.  
I'll be waiting for your reply on this, thanks.

**Comment by webdiscus** [comment]
Hi @YUCLing,

thank you for the issue report!

I'm very sorry, but is a really big problem to fix it, hardly possible, because Webpack self generates JS code and hasn't option to disable injection of HMR code.


Only one idea comes to mind. This is a "hack", of course, but it will work.
Pass the `isDev` variable into Pug template and use inline JS only if `isDev` is false.

Pass the `mode` into webpack.config.js:
packages.json
```json
{
  "scripts": {
    "start": "webpack serve --mode=development",
    "build": "webpack --mode=production --progress",
  },
}
```

webpack.config.js
```js
module.exports = (env, argv) => {
  const isDev = argv.mode === 'development';
  
  return {
    entry: {
      index: './src/views/home/index.pug',
    },
    plugins: [
      new PugPlugin(),
    ],
    module: {
      rules: [
        {
          test: /.pug$/,
          loader: PugPlugin.loader,
          options: {
            data: {
              isDev, // pass variable in all Pug files 
            }
          }
        },
      ],
    },
  };
}
```

Pug file
```pug
head
  if isDev
    script(src=require('./main.js') defer='defer')
  else
    script=require('./main.js?inline') 
body
```

**Comment by YUCLing** [comment]
Sad to hear this, but still appreciate your effort.

Since I can accept using extracted JS in dev mode, so the temporary hack works for me. 😃  
However, this will be helpful and can make the code simpler if there will be a solution found.

**Comment by webdiscus** [comment]
I will try to find a workaround for this problem.

**Comment by webdiscus** [comment]
@YUCLing 
I found the problem, I can fix it!

**Comment by webdiscus** [comment]
@YUCLing 

I have fixed the issue in `v4.9.2`.

**Comment by YUCLing** [comment]
Strange, I'm still getting unexpected output here...

Let me see if I can make a minimal reproduction. 😄

**Comment by webdiscus** [comment]
@YUCLing 

>  unexpected output

In `webpack serve` mode or by build too?

**Comment by YUCLing** [comment]
> @YUCLing
> 
> > unexpected output
> 
> In `webpack serve` mode or by build too?

Still `serve` only since I only use HMR in dev mode.

**Comment by webdiscus** [comment]
@YUCLing 

yes, inlined JS contains the HRM code (inc. source maps) and works in a Browser very well with reference to source file.

**Comment by webdiscus** [comment]
The same issue was described by [mini-css-extract-plugin issue](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/707).
It is a limitation of Webpack.
